export type ShippingRate = {
  name: string;
  total: number;
  excess: number;
};

export const G4S_RATES: Record<string, ShippingRate> = {
  athi_river: { name: "Athi River", total: 410, excess: 70 },
  awendo: { name: "Awendo", total: 690, excess: 70 },
  bomet: { name: "Bomet", total: 560, excess: 70 },
  bondo: { name: "Bondo", total: 750, excess: 70 },
  bungoma: { name: "Bungoma", total: 680, excess: 70 },
  busia: { name: "Busia", total: 750, excess: 70 },
  chogoria: { name: "Chogoria", total: 530, excess: 70 },
  chuka: { name: "Chuka", total: 480, excess: 70 },
  diani: { name: "Diani", total: 880, excess: 70 },
  eldama_ravine: { name: "Eldama Ravine", total: 540, excess: 70 },
  eldoret: { name: "Eldoret", total: 510, excess: 70 },
  emali: { name: "Emali", total: 680, excess: 70 },
  embu: { name: "Embu", total: 470, excess: 70 },
  garissa: { name: "Garissa", total: 840, excess: 70 },
  gatundu: { name: "Gatundu", total: 410, excess: 70 },
  gilgil: { name: "Gilgil", total: 400, excess: 70 },
  githunguri: { name: "Githunguri", total: 410, excess: 70 },
  hola: { name: "Hola", total: 2300, excess: 76 },
  homabay: { name: "Homa Bay", total: 810, excess: 70 },
  igoji: { name: "Igoji", total: 530, excess: 70 },
  isebania: { name: "Isebania", total: 840, excess: 70 },
  isiolo: { name: "Isiolo", total: 750, excess: 70 },
  isinya: { name: "Isinya", total: 480, excess: 70 },
  iten: { name: "Iten", total: 510, excess: 70 },
  kabarnet: { name: "Kabarnet", total: 670, excess: 70 },
  kagema: { name: "Kagema", total: 480, excess: 70 },
  kagio: { name: "Kagio", total: 470, excess: 70 },
  kajiado: { name: "Kajiado", total: 480, excess: 70 },
  kakamega: { name: "Kakamega", total: 540, excess: 70 },
  kakuma: { name: "Kakuma", total: 3370, excess: 113 },
  kampala: { name: "Kampala (Uganda)", total: 1620, excess: 86 },
  kangari: { name: "Kangari", total: 410, excess: 70 },
  kangundo: { name: "Kangundo", total: 480, excess: 70 },
  kapenguria: { name: "Kapenguria", total: 880, excess: 70 },
  kapsabet: { name: "Kapsabet", total: 710, excess: 70 },
  karatina: { name: "Karatina", total: 470, excess: 70 },
  kehancha: { name: "Kehancha", total: 840, excess: 70 },
  kericho: { name: "Kericho", total: 560, excess: 70 },
  keroka: { name: "Keroka", total: 690, excess: 70 },
  kerugoya: { name: "Kerugoya", total: 470, excess: 70 },
  kiambu: { name: "Kiambu", total: 410, excess: 70 },
  kibwezi: { name: "Kibwezi", total: 680, excess: 70 },
  kigajo: { name: "Kigajo", total: 470, excess: 70 },
  kijabe: { name: "Kijabe", total: 400, excess: 70 },
  kikuyu: { name: "Kikuyu", total: 410, excess: 70 },
  kilgoris: { name: "Kilgoris", total: 690, excess: 70 },
  kilifi: { name: "Kilifi", total: 950, excess: 70 },
  kimilili: { name: "Kimilili", total: 680, excess: 70 },
  kiriaini: { name: "Kiriaini", total: 480, excess: 70 },
  kisii: { name: "Kisii", total: 560, excess: 70 },
  kisumu: { name: "Kisumu", total: 560, excess: 70 },
  kitale: { name: "Kitale", total: 600, excess: 70 },
  kitengela: { name: "Kitengela", total: 410, excess: 70 },
  kitui: { name: "Kitui", total: 500, excess: 70 },
  kwale: { name: "Kwale", total: 880, excess: 70 },
  lamu: { name: "Lamu", total: 2300, excess: 76 },
  limuru: { name: "Limuru", total: 400, excess: 70 },
  litein: { name: "Litein", total: 560, excess: 70 },
  lodwar: { name: "Lodwar", total: 2300, excess: 113 },
  loitoktok: { name: "Loitoktok", total: 750, excess: 70 },
  lokichar: { name: "Lokichar", total: 1290, excess: 113 },
  lokichoggio: { name: "Lokichoggio", total: 3370, excess: 113 },
  londiani: { name: "Londiani", total: 560, excess: 70 },
  luanda: { name: "Luanda", total: 750, excess: 70 },
  lugari: { name: "Lugari", total: 680, excess: 70 },
  machakos: { name: "Machakos", total: 480, excess: 70 },
  makindu: { name: "Makindu", total: 680, excess: 70 },
  makutano: { name: "Makutano", total: 530, excess: 70 },
  makuyu: { name: "Makuyu", total: 410, excess: 70 },
  malaba: { name: "Malaba", total: 680, excess: 70 },
  malindi: { name: "Malindi", total: 950, excess: 70 },
  mandera: { name: "Mandera", total: 3510, excess: 130 },
  maralal: { name: "Maralal", total: 1230, excess: 86 },
  mariakani: { name: "Mariakani", total: 730, excess: 70 },
  marigat: { name: "Marigat", total: 670, excess: 70 },
  marsabit: { name: "Marsabit", total: 1080, excess: 86 },
  maseno: { name: "Maseno", total: 560, excess: 70 },
  matuu: { name: "Matuu", total: 480, excess: 70 },
  maua: { name: "Maua", total: 750, excess: 70 },
  mbale: { name: "Mbale", total: 540, excess: 70 },
  mbita: { name: "Mbita", total: 810, excess: 70 },
  meru: { name: "Meru", total: 530, excess: 70 },
  migori: { name: "Migori", total: 690, excess: 70 },
  mois_bridge: { name: "Mois Bridge", total: 600, excess: 70 },
  molo: { name: "Molo", total: 540, excess: 70 },
  mombasa: { name: "Mombasa", total: 730, excess: 70 },
  moyale: { name: "Moyale", total: 3510, excess: 130 },
  mtito_andei: { name: "Mtito Andei", total: 680, excess: 70 },
  mtwapa: { name: "Mtwapa", total: 730, excess: 70 },
  muhoroni: { name: "Muhoroni", total: 750, excess: 70 },
  mukurweini: { name: "Mukurweini", total: 470, excess: 70 },
  mumias: { name: "Mumias", total: 680, excess: 70 },
  muranga: { name: "Murang'a", total: 480, excess: 70 },
  murarandia: { name: "Murarandia", total: 480, excess: 70 },
  mwatate: { name: "Mwatate", total: 950, excess: 70 },
  mwea: { name: "Mwea", total: 470, excess: 70 },
  mwingi: { name: "Mwingi", total: 610, excess: 70 },
  nairobi: { name: "Nairobi", total: 350, excess: 70 },
  naivasha: { name: "Naivasha", total: 400, excess: 70 },
  nakuru: { name: "Nakuru", total: 400, excess: 70 },
  namanga: { name: "Namanga", total: 750, excess: 70 },
  nambale: { name: "Nambale", total: 750, excess: 70 },
  nandi_hills: { name: "Nandi Hills", total: 710, excess: 70 },
  nanyuki: { name: "Nanyuki", total: 600, excess: 70 },
  narok: { name: "Narok", total: 480, excess: 70 },
  naromoru: { name: "Naromoru", total: 600, excess: 70 },
  ngong: { name: "Ngong", total: 410, excess: 70 },
  njambini: { name: "Njambini", total: 480, excess: 70 },
  njoro: { name: "Njoro", total: 540, excess: 70 },
  nkubu: { name: "Nkubu", total: 530, excess: 70 },
  nyahururu: { name: "Nyahururu", total: 540, excess: 70 },
  nyamira: { name: "Nyamira", total: 560, excess: 70 },
  nyeri: { name: "Nyeri", total: 470, excess: 70 },
  ogembo: { name: "Ogembo", total: 690, excess: 70 },
  ol_kalou: { name: "Ol Kalou", total: 540, excess: 70 },
  ongata_rongai: { name: "Ongata Rongai", total: 410, excess: 70 },
  othaya: { name: "Othaya", total: 470, excess: 70 },
  oyugis: { name: "Oyugis", total: 690, excess: 70 },
  rachuonyo: { name: "Rachuonyo", total: 840, excess: 70 },
  rongo: { name: "Rongo", total: 690, excess: 70 },
  ruiru: { name: "Ruiru", total: 410, excess: 70 },
  runyenjes: { name: "Runyenjes", total: 480, excess: 70 },
  sabasaba: { name: "Sabasaba", total: 410, excess: 70 },
  sabatia: { name: "Sabatia", total: 540, excess: 70 },
  sagana: { name: "Sagana", total: 480, excess: 70 },
  siaya: { name: "Siaya", total: 750, excess: 70 },
  sondu: { name: "Sondu", total: 750, excess: 70 },
  sotik: { name: "Sotik", total: 560, excess: 70 },
  sultan_hamud: { name: "Sultan Hamud", total: 680, excess: 70 },
  tala: { name: "Tala", total: 480, excess: 70 },
  taveta: { name: "Taveta", total: 950, excess: 70 },
  thika: { name: "Thika", total: 410, excess: 70 },
  timau: { name: "Timau", total: 600, excess: 70 },
  turbo: { name: "Turbo", total: 510, excess: 70 },
  ugunja: { name: "Ugunja", total: 750, excess: 70 },
  ukunda: { name: "Ukunda", total: 880, excess: 70 },
  voi: { name: "Voi", total: 680, excess: 70 },
  wajir: { name: "Wajir", total: 2030, excess: 140 },
  watamu: { name: "Watamu", total: 950, excess: 70 },
  webuye: { name: "Webuye", total: 680, excess: 70 },
  wote: { name: "Wote", total: 680, excess: 70 },
  wundanyi: { name: "Wundanyi", total: 950, excess: 70 },
  yala: { name: "Yala", total: 560, excess: 70 },
};

export const TOWN_OPTIONS = Object.entries(G4S_RATES)
  .map(([key, rate]) => ({ key, name: rate.name }))
  .sort((a, b) => a.name.localeCompare(b.name));

/**
 * Calculate G4S shipping cost.
 * Base rate covers up to 5 kg. Each kg above 5 kg is charged at the excess rate.
 * Weight is rounded up to the nearest whole kg.
 */
export function calculateShipping(townKey: string, weightKg: number): number {
  const rate = G4S_RATES[townKey];
  if (!rate) return 0;
  const rounded = Math.ceil(weightKg);
  const extraKg = Math.max(0, rounded - 5);
  return rate.total + extraKg * rate.excess;
}
