CREATE TYPE "StockStatus" AS ENUM ('IN_STOCK', 'OUT_OF_STOCK', 'BACKORDER');
CREATE TYPE "ProductType" AS ENUM ('SIMPLE', 'VARIABLE');

ALTER TABLE "Product"
ADD COLUMN "sku" TEXT,
ADD COLUMN "shortDescription" TEXT,
ADD COLUMN "salePrice" DECIMAL(10,2),
ADD COLUMN "taxStatus" TEXT NOT NULL DEFAULT 'TAXABLE',
ADD COLUMN "taxClass" TEXT,
ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'KES',
ADD COLUMN "stockStatus" "StockStatus" NOT NULL DEFAULT 'IN_STOCK',
ADD COLUMN "weight" DECIMAL(10,2),
ADD COLUMN "length" DECIMAL(10,2),
ADD COLUMN "width" DECIMAL(10,2),
ADD COLUMN "height" DECIMAL(10,2),
ADD COLUMN "tags" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "metaTitle" TEXT,
ADD COLUMN "metaDescription" TEXT,
ADD COLUMN "productType" "ProductType" NOT NULL DEFAULT 'SIMPLE',
ADD COLUMN "isDownloadable" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "isVirtual" BOOLEAN NOT NULL DEFAULT false;

CREATE UNIQUE INDEX "Product_sku_key" ON "Product"("sku");
